create view v_informe_campania_por_departamento (total_encuestados , total_finalizados , representatividad , mes , anio , id_provincia , provincias , id_departamento , departamentos , instituciones , id_supervisor , matricula , abandono , riesgo_abandono , riesgo_repitencia , instituciones_abandono , instituciones_repitencia , aprobados , porcentaje_aprobados , aprobados_dificultad , porcentaje_aprobados_dificultad , desaprobados , porcentaje_desaprobados , instituciones_desaprobados , instituciones_aprobados_dificultad , inasistencia_docente , inasistencia_docente_mas_tres , cursos_inasistencia , instituciones_inasistencia_docente , inasistencia_alumnos , porcentaje_inasistencia_alumnos_enfermedad , porcentaje_inasistencia_alumnos_trabajo , porcentaje_inasistencia_alumnos_familiar , inasistencia_alumnos_mas_tres , instituciones_inasistencia_alumnos , solicitud_pase , ingresos , instituciones_ingresos , foco_uno , foco_dos_uno , foco_dos_dos , foco_tres , porcentaje_foco_uno , porcentaje_foco_dos_uno , porcentaje_foco_dos_dos , porcentaje_foco_tres , abandono_anterior , abandono_acumulado , riesgo_abandono_anterior , riesgo_abandono_acumulado , riesgo_repitencia_anterior , riesgo_repitencia_acumulado , aprobados_anterior , porcentaje_aprobados_anterior , aprobados_dificultad_anterior , porcentaje_aprobados_dificultad_anterior , desaprobados_anterior , porcentaje_desaprobados_anterior , inasistencia_docente_anterior , inasistencia_docente_acumulado , inasistencia_docente_mas_tres_anterior , inasistencia_docente_mas_tres_acumulado , inasistencia_alumnos_anterior , inasistencia_alumnos_acumulado , inasistencia_alumnos_mas_tres_anterior , inasistencia_alumnos_mas_tres_acumulado , solicitud_pase_anterior , solicitud_pase_acumulado , ingresos_anterior , ingresos_acumulado , foco_uno_anterior , foco_dos_uno_anterior , foco_dos_dos_anterior , foco_tres_anterior , porcentaje_foco_uno_anterior , porcentaje_foco_dos_uno_anterior , porcentaje_foco_dos_dos_anterior , porcentaje_foco_tres_anterior) as
    select 
        prov . *,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.abandono,
            0)) as abandono_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.abandono,
            0)) as abandono_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.riesgo_abandono,
            0)) as riesgo_abandono_anterior,
        '--' as riesgo_abandono_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.riesgo_repitencia,
            0)) as riesgo_repitencia_anterior,
        '--' as riesgo_repitencia_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.aprobados,
            0)) as aprobados_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_aprobados,
            0)) as porcentaje_aprobados_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.aprobados_dificultad,
            0)) as aprobados_dificultad_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_aprobados_dificultad,
            0)) as porcentaje_aprobados_dificultad_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.desaprobados,
            0)) as desaprobados_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_desaprobados,
            0)) as porcentaje_desaprobados_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.inasistencia_docente,
            0)) as inasistencia_docente_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.inasistencia_docente,
            0)) as inasistencia_docente_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.inasistencia_docente_mas_tres,
            0)) as inasistencia_docente_mas_tres_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.inasistencia_docente_mas_tres,
            0)) as inasistencia_docente_mas_tres_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.inasistencia_alumnos,
            0)) as inasistencia_alumnos_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.inasistencia_alumnos,
            0)) as inasistencia_alumnos_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.inasistencia_alumnos_mas_tres,
            0)) as inasistencia_alumnos_mas_tres_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.inasistencia_alumnos_mas_tres,
            0)) as inasistencia_alumnos_mas_tres_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.solicitud_pase,
            0)) as solicitud_pase_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.solicitud_pase,
            0)) as solicitud_pase_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.ingresos,
            0)) as ingresos_anterior,
        sum(if(prov_ant.mes <= prov.mes,
            prov_ant.ingresos,
            0)) as ingresos_acumulado,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.foco_uno,
            0)) as foco_uno_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.foco_dos_uno,
            0)) as foco_dos_uno_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.foco_dos_dos,
            0)) as foco_dos_dos_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.foco_tres,
            0)) as foco_tres_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_foco_uno,
            0)) as porcentaje_foco_uno_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_foco_dos_uno,
            0)) as porcentaje_foco_dos_uno_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_foco_dos_dos,
            0)) as porcentaje_foco_dos_dos_anterior,
        sum(if(prov_ant.mes = (prov.mes - 1),
            prov_ant.porcentaje_foco_tres,
            0)) as porcentaje_foco_tres_anterior
    from
        gema_cis_sms.v_campania_por_departamento prov
            join
        gema_cis_sms.v_campania_por_departamento prov_ant ON prov.id_provincia = prov_ant.id_provincia
            and prov.id_departamento = prov_ant.id_departamento
            and prov.anio = prov_ant.anio
    group by prov.id_departamento , prov.id_provincia , prov.mes , prov.anio;